### ISSUE TITLE
Задание 2 

### ISSUE THREAD

**Issue by djadjka** [Kernstall/Buyak-Practice#2]
1) Закинь файлы в папку, а не в корень
2) Оно норм быдет выглядеть на экране пк ?

**Comment by Kernstall** [comment]
Исправил, сделал папку с заданием. На пк шапка с футером растянется, а лента новостей особо не изменится. Как в ленте новостей вк например

**Comment by djadjka** [comment]
Меня скорее волнует панель фильтров :)

**Comment by Kernstall** [comment]
Потом станет виднее как лучше сделать, разместить фильтры справа/слева от ленты новостей или всплывающим меню как здесь.
![bootstr](https://user-images.githubusercontent.com/16035287/36352044-b129365a-14c3-11e8-88e2-7eb5f9a91542.png)

**Comment by djadjka** [comment]
Очень недурно, но есть мелкие несоответствия с тз, к сожалению в реальной жизни их надо соблюдать, даже если они кажутся нелогичными. Вам же мы доем некое поле для творчества, но минимум указанный в тз должен быть соблюден.
Если нужен максимальный бал, нужно дополнить в соответствии с тз
=)
